[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cronjob = "0.4.17"
polling = "3.1.0"
rand = "0.8.5"
reqwest = "0.11.22"
